functions
avagyan98/homeworks pull request #4
Opened 2023-01-29 18:45 UTC by avagyan98

2023-01-30 16:51 UTC, SaulReznik requested changes

2023-01-30 16:51 UTC, robhov97 commented on functions.js
> +        let firstX = x;
firstX is common for both cases, declare this variable in the upper scope and use it for both cases

2023-01-30 16:51 UTC, SaulReznik commented
you have a conflict

2023-01-31 15:36 UTC, avagyan98 commented on functions.js
> +        let firstX = x;
done

2023-02-01 15:52 UTC, SaulReznik approved these changes

2023-02-01 15:52 UTC, merged